### ISSUE TITLE
Amino.txt

### ISSUE THREAD

**Issue by arneelof** [Rostlab/LocNuclei#1]
The file Amino.txt is referred to in external_file_manager.py as.
        self._amino_file = '/usr/share/fastprofkernel/data/Amino.txt'

However, this file cannot be run and therefore the example cannot be executed.

Could you please provide this file..

**Comment by Eclipse19961229** [comment]
now do you have the file named Amino.txt???

**Comment by mariasche** [comment]
File was added to bl/data
