### ISSUE TITLE
ERROR:  File /usr/share/fastprofkernel/data/Amino.txt not available - exit!

### ISSUE THREAD

**Issue by Eclipse19961229** [Rostlab/LocNuclei#2]
When I ran the program, an error occurred .

D:\LocNuclei\LocNuclei>python locnuclei.py example/ example/ result.
Namespace(blast_folder='example/', blast_suffix='*.profile', debug=False, fas
asta_suffix='*.fasta', only_blast=False, output_file='result.out', temp_folde
 verbose=False)
ERROR:  File /usr/share/fastprofkernel/data/Amino.txt not available - exit!

however ,I can't find the file named Amino.txt

**Comment by mariasche** [comment]
I added the file to bl/data
